apiVersion: v1
kind: ConfigMap
metadata:
  name: ptob-service-config
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: ptob
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  APP_KAFKA_ENABLED: "true"
  APP_BEARER_TOKEN: local-dev-token
