FROM ghcr.io/cirruslabs/flutter:3.24.3 AS builder
WORKDIR /app

COPY . .
RUN flutter config --enable-web && \
    flutter create . --platforms web && \
    flutter pub get && \
    flutter build web --release

FROM nginx:1.27-alpine
COPY --from=builder /app/build/web /usr/share/nginx/html

EXPOSE 80
